[tool.poetry]
name = "space-invaders"
version = "0.1.0"
description = ""
authors = ["Niklas Mueller <n.mueller@medienagentur24.eu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
